language: python
dist: bionic   # required for Python >= 3.7

matrix:
  include:
    - python: 3.6
    - python: 3.7
#    - python: 3.8

# To install packages which are not on pip
before_install:
  - sudo apt-get update
  - sudo apt-get install gcc
  - sudo apt-get install libgfortran4

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - gcc

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install -r tests/test_requirements.txt

# commands to run tests
script:
  - black --check . --exclude docs/
  - coverage run --rcfile=.coveragerc --source pvcompare -m py.test
  - coverage report


after_success:
  - coveralls


#jobs:
#  include:
#    - stage: "Tests"                # naming the Tests stage
#      name: "Linting Tests"            # names the first Tests stage job
#      script: flake8
#      script: pylint
# for later stages
#    - script: ./integration-tests
#      name: "Integration Tests"     # names the second Tests stage job
#    - stage: deploy
#      name: "Deploy to GCP"
#      script: ./deploy

# blocklist
#branches:
#  except:
#  - branch_name1
#  - branch_name2

# safelist
#branches:
#  only:
#  - branch_name1
#  - branch_name2
