language: python
dist: xenial   # required for Python >= 3.7

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

# To install packages which are not on pip
#before_install:
#  - sudo apt-get install ...
#addons:
#  apt:
#    update: true

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install -r tests/test_requirements.txt

# commands to run tests
script:
  - coverage run --rcfile=.coveragerc --source pvcompare -m py.test
  - coverage report

after_success:
  - coveralls



#  - black --check . --exclude docs/  # todo for later

#jobs:
#  include:
#    - stage: "Tests"                # naming the Tests stage
#      name: "Linting Tests"            # names the first Tests stage job
#      script: flake8
#      script: pylint
# for later stages
#    - script: ./integration-tests
#      name: "Integration Tests"     # names the second Tests stage job
#    - stage: deploy
#      name: "Deploy to GCP"
#      script: ./deploy

# blocklist
#branches:
#  except:
#  - branch_name1
#  - branch_name2

# safelist
#branches:
#  only:
#  - branch_name1
#  - branch_name2
